### PR TITLE
Add macros for project directory, update .gitignore

### PR DESCRIPTION
**Pull request by kylebshr**
Added preprocessor macros for the project directory so that it doesn't need to be specified manually. Added bridging header necessary for exposing macros to Swift. Updated .gitignore with better rules.

### CODE REVIEW

**Comment by loiclec** [comment]
Thank you! All of these commits touch on things I don't feel comfortable about yet, so this is very appreciated. :)

**Comment by kylebshr** [comment]
Glad to help! The git stuff basically just ignores files that Xcode creates for anyone who opens the workspace, and any files that get generated from builds, testing, etc., that shouldn't actually be a part of the project. I hope the comments helped!

**Comment by loiclec** [comment]
So the instructions on how to start the demo server are invalid now, right? (those about changing the path to the correct directory)

**Comment by kylebshr** [comment]
That's right - I forgot to change that though! It's not necessary anymore.

**Comment by loiclec** [comment]
Great! and thanks again :)

**Pull request merged**
